const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const path = require('path');
require('dotenv').config();
const rateLimiter = require('./middleware/rateLimiter');
const apiRoutes = require('./routes/api');
const { initializeDatabase } = require('./config/database');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors());
app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json());
app.use(rateLimiter);
app.use(express.static(path.join(__dirname, '../public')));
app.use('/api', apiRoutes);
app.get('/login', (req, res) => { res.sendFile(path.join(__dirname, '../public/login.html')); });
app.get('/dashboard', (req, res) => { res.sendFile(path.join(__dirname, '../public/dashboard.html')); });
app.get('*', (req, res) => { res.sendFile(path.join(__dirname, '../public/index.html')); });
initializeDatabase().then(() => { app.listen(PORT, () => console.log(`[LIVE WORLD-CLASS] Website Romantis Dewi on port ${PORT}`)); });
module.exports = app;
